### ISSUE TITLE
Doesn't work with memory layers 

### ISSUE THREAD

**Issue by antoniusz** [nextgis/qgis_geometry_paster#11]

**Comment by ivanbarsukov** [comment]
Can you please provide more information? Did the layer have any attributes, or just geometry?

**Comment by jkr-wrk** [comment]
@antoniusz 

Could you try drawing a temporary part with the QGis Add Part function and then pasting your geometry over that part? I would like to know if it is similar to my bug.

**Comment by ivanbarsukov** [comment]
I am closing the issue because it is not reproducible. If it happens again, feel free to reopen.
