### ISSUE TITLE
Does not work when pasting to Geopackage with no initial Geometry

### ISSUE THREAD

**Issue by jkr-wrk** [nextgis/qgis_geometry_paster#14]
Probably related to bug does not work with Memory Layer, but not sure.

I have a Geopackage with a table with multipolygon geometry column. Selecting a geometry from another layer and pasting it to a feature works. Selecting a second feature and pasting it to a different feature gives an error.
Error: Paste geometry: Incompatible geometries. Trying to paste Polygon to UnknownGeometry

Workaround: Draw a geometry with Add Part. Then Paste the geometry with this tool.

I inspected the Geopackage as an Sqlite and the difference is:
At the start the GEOM column has value Null. And there are some tables missing. When adding the first feature it gets the value GP and all other features still have Null.
But when I add and remove a part with the Add Part / Remove Part function in QGis the feature gets GP even if it has no parts anymore. And then pasting geometry keeps working.

**Comment by ivanbarsukov** [comment]
Thank you for reporting the issue. This bug has been fixed in  https://github.com/nextgis/qgis_geometry_paster/pull/15 and is included in the release of version 0.4.
