### ISSUE TITLE
Icon Does Not Appear In QGIS

### ISSUE THREAD

**Issue by Lumba2** [nextgis/qgis_geometry_paster#9]
In QGIS newest version 3.32.0 Geometry Paster won't show up. The installation of the plugin seems to be OK, The files are in the right directory, the plugin is activated. Nevertheless I can't find it in 'Menu Bar/Plugins/'.

**Comment by ivanbarsukov** [comment]
"Geometry Paster" does not add items to this menu. It adds items in 'Menu Bar/Edit' and digitizing toolbar as 'Paste Geometry'. You can also use Ctrl+Shift+G combination. Example of work in the video https://www.youtube.com/watch?v=NMs5hDf5ndE. Fell free to reopen this issue if needed
